name: deploy-backend

on:
  workflow_call:
    inputs:
        environment: 
            description: "Environment deploy"
            required: true
            type: string
        node-version:
            description: "Version for NodeJS"
            required: false
            type: string
            default: "18.x"
        build-command:
            description: "Nodejs build command"
            required: false
            type: string
            default: "npm run build"
        aws-region:
            description: "The AWS region"
            default: us-east-1
            required: false
            type: string
        function-name:
            description: "Lambda function name"
            required: true
            type: string
        files-to-compress:
            description: "Files to compress and upload in aws"
            required: true
            type: string
    secrets:
        ENV_VARS:
            required: false
        AWS_ROLE_DEPLOY_BACKEND:
            required: true

permissions:
  id-token: write
  contents: read

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Setup Node
              uses: actions/setup-node@v1
              with:
                node-version: ${{ inputs.node-version }}
            - name: Restore cache
              id: restore-cache
              uses: actions/cache@v3
              env:
                cache-name: node-modules-dev
              with:
                path: node_modules
                key: npm-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
            - name: Install Dependencies
              if: steps.restore-cache.outputs.cache-hit != 'true'
              run: |
                npm ci
            - name: Run Build
              run: ${{ inputs.build-command }}
            - name: Persist Build
              uses: actions/upload-artifact@v2
              with:
                name: Build
                path: build
                retention-days: 1
                if-no-files-found: error

    deploy-lambda-aws:
        runs-on: ubuntu-latest
        environment: ${{ inputs.environment }}
        needs:
            - build
        steps:
            - uses: actions/checkout@v3
            - name: Setup Node
              uses: actions/setup-node@v1
              with:
                node-version: ${{ inputs.node-version }}
            - name: Restore Build
              uses: actions/download-artifact@v2
              with:
                name: Build
                path: build
            - name: Restore Cache
              uses: actions/cache@v3
              id: restore-cache
              env:
                cache-name: node-modules-prod
              with:
                path: node_modules
                key: npm-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
            - name: Install Dependencies
              if: steps.restore-cache.outputs.cache-hit != 'true'
              run: |
                npm ci --only=prod
            - name: Configure AWS Credentials
              uses: aws-actions/configure-aws-credentials@v2
              with:
                role-to-assume: ${{ secrets.AWS_ROLE_DEPLOY_BACKEND }}
                aws-region: ${{ inputs.aws-region }}
            - name: Deploy AWS Lambda
              env:
                FUNCTION_NAME: ${{ inputs.function-name }}
                ENV_VARS: ${{ secrets.ENV_VARS }}
                AWS_REGION: ${{ inputs.aws-region }}
                FILES_TO_COMPRESS: ${{ inputs.files-to-compress }}
              run: |
                echo "Set environment variables"
                VARS=$(echo $ENV_VARS | tr " " "\n")
                for var in $VARS; do
                    env_config=(${var//=/ })
                    env_name=${env_config[0]}
                    env_value=${env_config[1]}
                    printf -v "$env_name" "$env_value"
                    array_vars="${array_vars}\"${env_name}\":\"${env_value}\","
                done
                env_vars="{\"Variables\":{${array_vars%?}}}"

                echo "Deploying Lambda"
                aws lambda update-function-configuration \
                    --function-name $FUNCTION_NAME \
                    --environment $env_vars \
                    --region $AWS_REGION

                echo "Uploading lambda function's code..."
                echo "Compressing lambda function's files..."
                zip -qq -r payload.zip $FILES_TO_COMPRESS

                aws lambda update-function-code --function-name $FUNCTION_NAME --publish --zip-file fileb://payload.zip --region $AWS_REGION 
                
                
            


