name: requirements-backend

on:
  workflow_call:
    inputs:
      project-key:
        description: 'Project key wich is gonna be the project identifier in Sonarcloud'
        required: true
        type: string
      organization:
        description: 'Organization name in github and sonar'
        required: false
        default: "pawsly-connect"
        type: string

jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Analyze with SonarCloud
      uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      with:
        args: >
          -Dsonar.branch.target=${{ github.event.pull_request.base.ref }}
          -Dsonar.branch.name=${{ github.event.pull_request.base.ref }}
          -Dsonar.projectKey=${{ inputs.project-key }}
          -Dsonar.organization=${{ inputs.organization }}
    - name: SonarCloud Verify results
      shell: bash
      run: |
        state_sonar=$(curl --location --request GET 'https://sonarcloud.io/api/qualitygates/project_status?projectKey=${{ inputs.organization }}_${{ inputs.project-name }}&branch=${{ github.event.pull_request.head.ref }}' | jq '.projectStatus.status')
        if [ "$state_sonar" != "\"OK\"" ]; then echo "Quality Gate with state: $state_sonar"; exit 1; else echo "Quality Gate OK"; exit 0; fi
